name: ${project.name}
version: ${project.version}
description: ${project.description}
author: DarkBlade12
website: ${project.url}
api-version: 1.13

main: com.darkblade12.enchantplus.EnchantPlus

commands:
  plus:
    description: General EnchantPlus command
    usage: /plus
    aliases: [ep, eplus, enchantplus]