name: EnchantPlus
version: 1.3.4
author: DarkBlade12
website: http://dev.bukkit.org/profiles/DarkBladee12
api-version: 1.13

main: com.darkblade12.enchantplus.EnchantPlus

commands:
  plus:
    description: General EnchantPlus command
    usage: /plus
    aliases: [ep, eplus, enchantplus]