name: EnchantPlus
version: 1.3.3
author: DarkBlade12
website: http://dev.bukkit.org/profiles/DarkBladee12

main: com.darkblade12.enchantplus.EnchantPlus

commands:
  plus:
    description: General EnchantPlus command
    usage: /plus
    aliases: [ep, eplus, enchantplus]